
services:
  - docker:dind

stages:
  - build
  - deploy

build:
  image: docker:latest
  stage: build
  script:
    - docker build -t python_ucb .
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - ssh london date
  # only:
  #   - production
  tags:
    - docker
