stages:
  - build
  # - deploy
build:
  image: docker:latest
  stage: build
  script:
    - docker build -t python_ucb .
  # only:
  #   - production
  tags:
    - docker
# deploy:
#   image: stackahoy/stackahoy-cli
#   stage: deploy
#   script:
#     - stackahoy deploy -t $STACKAHOY_TOKEN -b production -r $REPO_ID --skip-delivery
#   only:
#     - production
#   tags:
#     - docker
