image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t python_ucb .
  tags:
    - docker

deploy:
  image: stackahoy/stackahoy-cli
  stage: deploy
  script:
    - stackahoy deploy -t $STACKAHOY_TOKEN -b production -r $REPO_ID --skip-delivery
  # only:
  #   - production
  tags:
    - docker
