version: '2'
services:
  web:
    build: .
    ports:
      - '443:443'
    volumes:
      - ./storage:/storage
      - /etc/letsencrypt/live/python-ucb/cert.pem:/cert.pem
      - /etc/letsencrypt/live/python-ucb/cert.key:/cert.key
