version: '2'
services:
  web:
    build: .
    ports:
      - '443:443'
    volumes:
      - ./storage:/storage
      - /etc/letsencrypt/live/fabiendob.at/cert.pem:/cert.pem
      - /etc/letsencrypt/live/fabiendob.at/privkey.pem:/cert.key
